// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	sendStatus: (status: CourseStatus) => __TAURI_INVOKE<null>("send_status", { status }),
	/**  获取包含版本及作者信息的应用元数据。 */
	metadata: () => __TAURI_INVOKE<MetadataConfig>("metadata"),
	options: () => __TAURI_INVOKE<OptionsConfig>("options"),
	setOptions: (options: OptionsConfig) => __TAURI_INVOKE<void>("set_options", { options }),
	/**  获取当前可用的全部大语言模型提供商列表。 */
	providers: () => __TAURI_INVOKE<string[]>("providers"),
	/**  获取当前选中的大语言模型提供商。 */
	currentProvider: () => __TAURI_INVOKE<string>("current_provider"),
	/**  将当前大语言模型提供商切换为指定提供商。 */
	switchProvider: (provider: string) => __TAURI_INVOKE<null>("switch_provider", { provider }),
	/**  获取当前大语言模型提供商所支持的全部模型列表。 */
	models: () => __TAURI_INVOKE<string[]>("models"),
	/**  获取当前大语言模型提供商正在使用的具体模型名称。 */
	currentModel: () => __TAURI_INVOKE<string>("current_model"),
	/**  将当前大语言模型提供商的选用模型切换为指定模型。 */
	switchModel: (model: string) => __TAURI_INVOKE<void>("switch_model", { model }),
	apiKey: () => __TAURI_INVOKE<string>("api_key"),
	/**  设置当前大语言模型提供商的 API 密钥。 */
	setKey: (key: string) => __TAURI_INVOKE<null>("set_key", { key }),
	/**  将内存中的全局配置持久化保存至本地文件。 */
	saveConfig: () => __TAURI_INVOKE<null>("save_config"),
	/**  从本地 Ollama 服务拉取可用模型列表更新至内存配置。 */
	fetchOllamaModels: () => __TAURI_INVOKE<null>("fetch_ollama_models"),
	setZoom: (scale: number | null) => __TAURI_INVOKE<null>("set_zoom", { scale }),
	canGoBack: () => __TAURI_INVOKE<boolean>("can_go_back"),
	canGoForward: () => __TAURI_INVOKE<boolean>("can_go_forward"),
	goHome: () => __TAURI_INVOKE<null>("go_home"),
	goBack: () => __TAURI_INVOKE<null>("go_back"),
	goForward: () => __TAURI_INVOKE<null>("go_forward"),
	currentUrl: () => __TAURI_INVOKE<string | null>("current_url"),
	reload: () => __TAURI_INVOKE<null>("reload"),
	/**  带有渐隐过渡效果的应用窗口关闭指令。 */
	close: () => __TAURI_INVOKE<void>("close"),
	/**  应用窗口最小化处理指令。 */
	minimize: () => __TAURI_INVOKE<void>("minimize"),
};

/* Types */
export type ChapterProgressPayload = {
	index: number,
	completed: number,
	title: string,
};

export type CourseStatus = "waiting" | "started" | ({ totalProgress: TotalProgressPayload }) & { chapterProgress?: never; tabProgress?: never; taskProgress?: never } | ({ chapterProgress: ChapterProgressPayload }) & { tabProgress?: never; taskProgress?: never; totalProgress?: never } | ({ tabProgress: TabProgressPayload }) & { chapterProgress?: never; taskProgress?: never; totalProgress?: never } | ({ taskProgress: TaskProgressPayload }) & { chapterProgress?: never; tabProgress?: never; totalProgress?: never } | "cancelled" | "finished";

export type MetadataConfig = {
	author?: string,
	title?: string,
	version?: string,
	homeUrl?: string,
	logLevel?: string,
};

export type OptionsConfig = {
	persistSession?: boolean,
	muteWebview?: boolean,
	speedLock?: boolean,
	speedValue?: number | null,
};

export type TabProgressPayload = {
	total: number,
	index: number,
};

export type TaskProgressPayload = {
	index: number,
	category: string,
};

export type TotalProgressPayload = {
	total: number,
	title: string,
};

